# Generated by Django 6.0.7 on 2026-07-26 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=20, unique=True)),
                ('asset_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty_expiry', models.DateField()),
                ('current_status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Under Maintenance', 'Under Maintenance'), ('Damaged', 'Damaged'), ('Lost', 'Lost'), ('Retired', 'Retired')], default='Available', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.assetcategory')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.vendor')),
            ],
        ),
    ]
