# Generated by Django 6.0.7 on 2026-07-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
